/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prizma.svevendas.view;

import com.prizma.svevendas.dao.CustomersDAO;
import com.prizma.svevendas.dao.EmployeesDAO;
import com.prizma.svevendas.model.Customers;
import com.prizma.svevendas.model.Employees;
import com.prizma.svevendas.utils.CleanFields;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alenc
 */
public class frmEmployees extends javax.swing.JFrame {

    public void listTable() {
        EmployeesDAO cdao = new EmployeesDAO();
        List<Employees> list = cdao.listEmployees();
        // Call DefaultTableModel
        DefaultTableModel dtb = (DefaultTableModel) table.getModel();
        // Set Colums rows
        dtb.setNumRows(0);
        // for 
        for (Employees emp : list) {
            // put dtb -> list
            dtb.addRow(new Object[]{
                emp.getId(),
                emp.getName(),
                emp.getRg(),
                emp.getCpf(),
                emp.getEmail(),
                emp.getPasswd(),
                emp.getPosition(),
                emp.getLevelAccess(),
                emp.getPhone(),
                emp.getMovel(),
                emp.getCep(),
                emp.getAddress(),
                emp.getComplement(),
                emp.getNumberHouse(),
                emp.getCity(),
                emp.getStreet(),
                emp.getState()

            });
        }
    }

    /**
     * Creates new form frmCustomers
     */
    public frmEmployees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsult = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelGuides = new javax.swing.JTabbedPane();
        panelConsultClient = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_name_cc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_search_cc = new javax.swing.JButton();
        panelPersonalData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_rg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        txt_complement = new javax.swing.JTextField();
        txt_number = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        txt_street = new javax.swing.JTextField();
        cbx_state = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        txt_phone = new javax.swing.JFormattedTextField();
        txt_movel = new javax.swing.JFormattedTextField();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_cep = new javax.swing.JFormattedTextField();
        txt_passwd = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        cbLevelAccess = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_position = new javax.swing.JTextField();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Funcionários");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelConsult.setBackground(new java.awt.Color(255, 32, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulário de Funcionários");

        javax.swing.GroupLayout jPanelConsultLayout = new javax.swing.GroupLayout(jPanelConsult);
        jPanelConsult.setLayout(jPanelConsultLayout);
        jPanelConsultLayout.setHorizontalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(341, 341, 341))
        );
        jPanelConsultLayout.setVerticalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel16.setText("Nome:");

        txt_name_cc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_name_ccKeyReleased(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "Email", "Senha", "Cargo", "Nivel_Acesso", "Telefone", "Celular", "Cep", "Endereço", "Complemento", "Nº", "Cidade", "Bairro", "Estado"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btn_search_cc.setText("Pesquisar");
        btn_search_cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_ccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultClientLayout = new javax.swing.GroupLayout(panelConsultClient);
        panelConsultClient.setLayout(panelConsultClientLayout);
        panelConsultClientLayout.setHorizontalGroup(
            panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                    .addGroup(panelConsultClientLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_name_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search_cc)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelConsultClientLayout.setVerticalGroup(
            panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultClientLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_name_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_cc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelGuides.addTab("Consulta de Funcionários", panelConsultClient);

        jLabel2.setText("Código:");

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        txt_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nameMouseClicked(evt);
            }
        });
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });

        jLabel4.setText("RG:");

        jLabel5.setText("CPF:");

        jLabel6.setText("E-mail:");

        jLabel7.setText("Telefone:");

        jLabel8.setText("Celular:");

        jLabel9.setText("CEP:");

        jLabel10.setText("Endereço:");

        jLabel11.setText("Complemento:");

        jLabel12.setText("Nº:");

        jLabel13.setText("Cidade:");

        jLabel14.setText("Bairro:");

        jLabel15.setText("UF:");

        cbx_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        btn_search.setText("Pesquisar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        try {
            txt_phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_movel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_movel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_movelActionPerformed(evt);
            }
        });

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setText("Senha:");

        cbLevelAccess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário" }));

        jLabel18.setText("Cargo:");

        javax.swing.GroupLayout panelPersonalDataLayout = new javax.swing.GroupLayout(panelPersonalData);
        panelPersonalData.setLayout(panelPersonalDataLayout);
        panelPersonalDataLayout.setHorizontalGroup(
            panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_search))
                    .addComponent(txt_cpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(txt_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_position))
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_movel))
                            .addComponent(cbLevelAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_street))
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_complement, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_number))
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        panelPersonalDataLayout.setVerticalGroup(
            panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btn_search)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txt_complement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbx_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(txt_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_movel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLevelAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelGuides.addTab("Dados Pessoais", panelPersonalData);

        btn_new.setText("Novo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setText("Salvar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_edit.setText("Editar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Excluir");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_print.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConsult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGuides)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_new, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete)
                                .addGap(17, 17, 17)
                                .addComponent(btn_print)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGuides, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_print))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // Capture vizualization data and send to database
        Employees emp = new Employees();

        emp.setName(txt_name.getText());
        emp.setRg(txt_rg.getText());
        emp.setCpf(txt_cpf.getText());
        emp.setEmail(txt_email.getText());
        emp.setPasswd(txt_passwd.getText());
        emp.setPosition(txt_position.getText());
        emp.setLevelAccess(cbLevelAccess.getSelectedItem().toString());
        emp.setPhone(txt_phone.getText());
        emp.setMovel(txt_movel.getText());
        emp.setCep(txt_cep.getText());
        emp.setAddress(txt_address.getText());
        emp.setNumberHouse(Integer.parseInt(txt_number.getText()));
        emp.setComplement(txt_complement.getText());
        emp.setCity(txt_city.getText());
        emp.setStreet(txt_street.getText());
        emp.setState(cbx_state.getSelectedItem().toString());

        // Call method saveDAO
        EmployeesDAO edao = new EmployeesDAO();
        edao.save(emp);
        CleanFields cls = new CleanFields();
        cls.cleanForm(panelPersonalData);

    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // Capture this.name in txt_name
        String name = txt_name.getText();
        Customers ctm = new Customers();
        CustomersDAO cdao = new CustomersDAO();
        // New customer = cdao -> method search
        ctm = cdao.Search(name);
        // if name != null
        if (ctm.getName() != null) {
            txt_id.setText(String.valueOf(ctm.getId()));
            txt_name.setText(ctm.getName());
            txt_rg.setText(ctm.getRg());
            txt_cpf.setText(ctm.getCpf());
            txt_email.setText(ctm.getEmail());
            txt_phone.setText(ctm.getPhone());
            txt_movel.setText(ctm.getMovel());
            txt_cep.setText(ctm.getCep());
            txt_address.setText(ctm.getAddress());
            txt_number.setText(String.valueOf(ctm.getNumberHouse()));
            txt_complement.setText(ctm.getComplement());
            txt_city.setText(ctm.getCity());
            txt_street.setText(ctm.getStreet());
            cbx_state.setSelectedItem(ctm.getState());
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // Clean Fields for new form
        CleanFields cleanForm = new CleanFields();
        cleanForm.cleanForm(panelPersonalData);
    }//GEN-LAST:event_btn_newActionPerformed

    private void txt_movelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_movelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_movelActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTable();
    }//GEN-LAST:event_formWindowActivated

    private void btn_search_ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_ccActionPerformed
        // Capture text digit
        String name = "%" + txt_name_cc.getText() + "%";

        EmployeesDAO edao = new EmployeesDAO();
        // get String name passed -> sql
        List<Employees> list = edao.listSearchFilter(name);
        // Call DefaultTableModel
        DefaultTableModel dtb = (DefaultTableModel) table.getModel();
        // Set Colums rows
        dtb.setNumRows(0);
        // for 
        for (Employees emp : list) {
            // put dtb -> list
            dtb.addRow(new Object[]{
                emp.getId(),
                emp.getName(),
                emp.getRg(),
                emp.getCpf(),
                emp.getEmail(),
                emp.getPasswd(),
                emp.getPosition(),
                emp.getLevelAccess(),
                emp.getPhone(),
                emp.getMovel(),
                emp.getCep(),
                emp.getAddress(),
                emp.getComplement(),
                emp.getNumberHouse(),
                emp.getCity(),
                emp.getStreet(),
                emp.getState()

            });
        }
    }//GEN-LAST:event_btn_search_ccActionPerformed

    private void txt_name_ccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_name_ccKeyReleased
        // Capture text digit
        String name = "%" + txt_name_cc.getText() + "%";

        EmployeesDAO edao = new EmployeesDAO();
        // get String name passed -> sql
        List<Employees> list = edao.listSearchFilter(name);
        // Call DefaultTableModel
        DefaultTableModel dtb = (DefaultTableModel) table.getModel();
        // Set Colums rows
        dtb.setNumRows(0);
        // for 
        for (Employees emp : list) {
            // put dtb -> list
            dtb.addRow(new Object[]{
                emp.getId(),
                emp.getName(),
                emp.getRg(),
                emp.getCpf(),
                emp.getEmail(),
                emp.getPasswd(),
                emp.getPosition(),
                emp.getLevelAccess(),
                emp.getPhone(),
                emp.getMovel(),
                emp.getCep(),
                emp.getAddress(),
                emp.getComplement(),
                emp.getNumberHouse(),
                emp.getCity(),
                emp.getStreet(),
                emp.getState()

            });
        }
    }//GEN-LAST:event_txt_name_ccKeyReleased

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed
        // if event key equals ENTER 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Capture this.name in txt_name
            String name = txt_name.getText();
            Employees emp = new Employees();
            EmployeesDAO edao = new EmployeesDAO();
            // New customer = cdao -> method search
            emp = edao.Search(name);
            // if name != null
            if (emp.getName() != null) {
                txt_id.setText(String.valueOf(emp.getId()));
                txt_name.setText(emp.getName());
                txt_rg.setText(emp.getRg());
                txt_cpf.setText(emp.getCpf());
                txt_email.setText(emp.getEmail());
                txt_passwd.setText(emp.getPasswd());
                txt_position.setText(emp.getPosition());
                cbLevelAccess.setSelectedItem(emp.getLevelAccess());
                txt_phone.setText(emp.getPhone());
                txt_movel.setText(emp.getMovel());
                txt_cep.setText(emp.getCep());
                txt_address.setText(emp.getAddress());
                txt_number.setText(String.valueOf(emp.getNumberHouse()));
                txt_complement.setText(emp.getComplement());
                txt_city.setText(emp.getCity());
                txt_street.setText(emp.getStreet());
                cbx_state.setSelectedItem(emp.getState());
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
            }
        }

    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMouseClicked

    }//GEN-LAST:event_txt_nameMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // Select Guide to capture and transfer datas other guide
        panelGuides.setSelectedIndex(0);
        txt_id.setText(table.getValueAt(table.getSelectedRow(), 0).toString());
        txt_name.setText(table.getValueAt(table.getSelectedRow(), 1).toString());
        txt_rg.setText(table.getValueAt(table.getSelectedRow(), 2).toString());
        txt_cpf.setText(table.getValueAt(table.getSelectedRow(), 3).toString());
        txt_email.setText(table.getValueAt(table.getSelectedRow(), 4).toString());
        txt_passwd.setText(table.getValueAt(table.getSelectedRow(), 5).toString());
        txt_position.setText(table.getValueAt(table.getSelectedRow(), 6).toString());
        cbLevelAccess.setSelectedItem(table.getValueAt(table.getSelectedRow(), 7).toString());
        txt_phone.setText(table.getValueAt(table.getSelectedRow(), 8).toString());
        txt_movel.setText(table.getValueAt(table.getSelectedRow(), 9).toString());
        txt_cep.setText(table.getValueAt(table.getSelectedRow(), 10).toString());
        txt_address.setText(table.getValueAt(table.getSelectedRow(), 11).toString());
        txt_complement.setText(table.getValueAt(table.getSelectedRow(), 12).toString());
        txt_number.setText(table.getValueAt(table.getSelectedRow(), 13).toString());        
        txt_street.setText(table.getValueAt(table.getSelectedRow(), 14).toString());
        txt_city.setText(table.getValueAt(table.getSelectedRow(), 15).toString());
        cbx_state.setSelectedItem(table.getValueAt(table.getSelectedRow(), 16).toString());

    }//GEN-LAST:event_tableMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // edit and save
        Employees emp = new Employees();

        emp.setName(txt_name.getText());
        emp.setRg(txt_rg.getText());
        emp.setCpf(txt_cpf.getText());
        emp.setEmail(txt_email.getText());
        emp.setPasswd(txt_passwd.getText());
        emp.setPosition(txt_position.getText());
        emp.setLevelAccess(cbLevelAccess.getSelectedItem().toString());
        emp.setPhone(txt_phone.getText());
        emp.setMovel(txt_movel.getText());
        emp.setCep(txt_cep.getText());
        emp.setAddress(txt_address.getText());
        emp.setNumberHouse(Integer.parseInt(txt_number.getText()));
        emp.setComplement(txt_complement.getText());
        emp.setCity(txt_city.getText());
        emp.setStreet(txt_street.getText());
        emp.setState(cbx_state.getSelectedItem().toString());
        emp.setId(Integer.valueOf(txt_id.getText()));

        // Call method saveDAO
        EmployeesDAO edao = new EmployeesDAO();
        edao.edit(emp);
        CleanFields cls = new CleanFields();
        cls.cleanForm(panelPersonalData);

    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        //Action delete customer for id
        Employees emp = new Employees();
        emp.setId(Integer.valueOf(txt_id.getText()));
        EmployeesDAO edao = new EmployeesDAO();
        edao.delete(emp);
        // clear fields 
        CleanFields clean = new CleanFields();
        clean.cleanForm(panelPersonalData);
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search_cc;
    private javax.swing.JComboBox<String> cbLevelAccess;
    private javax.swing.JComboBox<String> cbx_state;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelConsult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelConsultClient;
    private javax.swing.JTabbedPane panelGuides;
    private javax.swing.JPanel panelPersonalData;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_address;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_complement;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JFormattedTextField txt_movel;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_name_cc;
    private javax.swing.JTextField txt_number;
    private javax.swing.JPasswordField txt_passwd;
    private javax.swing.JFormattedTextField txt_phone;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_street;
    // End of variables declaration//GEN-END:variables
}
