/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prizma.svevendas.view;

import com.prizma.svevendas.dao.CustomersDAO;
import com.prizma.svevendas.dao.ProductDAO;
import com.prizma.svevendas.dao.SuppliersDAO;
import com.prizma.svevendas.model.Customers;
import com.prizma.svevendas.model.Product;
import com.prizma.svevendas.model.Suppliers;
import com.prizma.svevendas.utils.CleanFields;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alenc
 */
public class frmProducts extends javax.swing.JFrame {

    public void listTable() {
        ProductDAO pdao = new ProductDAO();
        List<Product> list = pdao.listProduct();
        // Call DefaultTableModel
        DefaultTableModel dtb = (DefaultTableModel) table.getModel();
        // Set Colums rows
        dtb.setNumRows(0);
        // for 
        for (Product prd : list) {
            // put dtb -> list
            dtb.addRow(new Object[]{
                prd.getId(),
                prd.getDescribe(),
                prd.getPrice(),
                prd.getQtd_Stock(),
                prd.getSuppliers().getName()

            });
        }
    }

    /**
     * Creates new form frmCustomers
     */
    public frmProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsult = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelGuides = new javax.swing.JTabbedPane();
        panelConsultClient = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_describe_cc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_search_describe = new javax.swing.JButton();
        panelPersonalData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_describe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbx_suppliers = new javax.swing.JComboBox();
        btn_search = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelConsult.setBackground(new java.awt.Color(255, 32, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanelConsultLayout = new javax.swing.GroupLayout(jPanelConsult);
        jPanelConsult.setLayout(jPanelConsultLayout);
        jPanelConsultLayout.setHorizontalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
        );
        jPanelConsultLayout.setVerticalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel16.setText("Descrição:");

        txt_describe_cc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_describe_ccKeyReleased(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Preço", "Qtd. Produtos", "Fornecedor"
            }
        ));
        table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btn_search_describe.setText("Pesquisar");
        btn_search_describe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_describeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultClientLayout = new javax.swing.GroupLayout(panelConsultClient);
        panelConsultClient.setLayout(panelConsultClientLayout);
        panelConsultClientLayout.setHorizontalGroup(
            panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(panelConsultClientLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_describe_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search_describe)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelConsultClientLayout.setVerticalGroup(
            panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultClientLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelConsultClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_describe_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_describe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelGuides.addTab("Consulta de Produtos", panelConsultClient);

        jLabel2.setText("Código:");

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição:");

        txt_describe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_describeMouseClicked(evt);
            }
        });
        txt_describe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_describeActionPerformed(evt);
            }
        });
        txt_describe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_describeKeyPressed(evt);
            }
        });

        jLabel4.setText("Preço:");

        jLabel6.setText("Qtd. Estoque");

        jLabel15.setText("Fornecedor:");

        cbx_suppliers.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbx_suppliersAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbx_suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_suppliersMouseClicked(evt);
            }
        });
        cbx_suppliers.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbx_suppliersComponentShown(evt);
            }
        });

        btn_search.setText("Pesquisar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonalDataLayout = new javax.swing.GroupLayout(panelPersonalData);
        panelPersonalData.setLayout(panelPersonalDataLayout);
        panelPersonalDataLayout.setHorizontalGroup(
            panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addComponent(txt_describe, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_search))))
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 240, Short.MAX_VALUE))
        );
        panelPersonalDataLayout.setVerticalGroup(
            panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_describe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbx_suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        panelGuides.addTab("Dados do Produto", panelPersonalData);

        btn_new.setText("Novo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setText("Salvar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_edit.setText("Editar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Excluir");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_print.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConsult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGuides)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_new, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete)
                                .addGap(17, 17, 17)
                                .addComponent(btn_print)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGuides, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_print))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        Product prd = new Product();

        prd.setDescribe(txt_describe.getText());
        prd.setPrice(Double.parseDouble(txt_price.getText()));
        prd.setQtd_Stock(Integer.parseInt(txt_stock.getText()));

        // recovery id
        System.out.println(cbx_suppliers.getSelectedItem().toString());
        prd.setSuppliers((Suppliers) cbx_suppliers.getSelectedItem());

        // Call method saveDAO
        ProductDAO pdao = new ProductDAO();
        pdao.save(prd);
        CleanFields cls = new CleanFields();
        cls.cleanForm(panelPersonalData);

    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // Capture this.name in txt_name
//        String name = txt_describe.getText();
//        Customers ctm = new Customers();
//        CustomersDAO cdao = new CustomersDAO();
//        // New customer = cdao -> method search
//        ctm = cdao.Search(name);
//        // if name != null
//        if (ctm.getName() != null) {
//            txt_id.setText(String.valueOf(ctm.getId()));
//            txt_describe.setText(ctm.getName());
//            txt_price.setText(ctm.getRg());
//            txt_cpf.setText(ctm.getCpf());
//            txt_stock.setText(ctm.getEmail());
//            txt_phone.setText(ctm.getPhone());
//            txt_movel.setText(ctm.getMovel());
//            txt_cep.setText(ctm.getCep());
//            txt_address.setText(ctm.getAddress());
//            txt_number.setText(String.valueOf(ctm.getNumberHouse()));
//            txt_complement.setText(ctm.getComplement());
//            txt_city.setText(ctm.getCity());
//            txt_street.setText(ctm.getStreet());
//            cbx_employees.setSelectedItem(ctm.getState());
//        } else {
//            JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
//        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // Clean Fields for new form
        CleanFields cleanForm = new CleanFields();
        cleanForm.cleanForm(panelPersonalData);
    }//GEN-LAST:event_btn_newActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTable();
    }//GEN-LAST:event_formWindowActivated

    private void btn_search_describeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_describeActionPerformed
        // Capture text digit
        String name = "%" + txt_describe_cc.getText() + "%";

        CustomersDAO cdao = new CustomersDAO();
        // get String name passed -> sql
        List<Customers> list = cdao.listSearchFilter(name);
        // Call DefaultTableModel
        DefaultTableModel dtb = (DefaultTableModel) table.getModel();
        // Set Colums rows
        dtb.setNumRows(0);
        // for 
        for (Customers ctm : list) {
            // put dtb -> list
            dtb.addRow(new Object[]{
                ctm.getId(),
                ctm.getName(),
                ctm.getRg(),
                ctm.getCpf(),
                ctm.getEmail(),
                ctm.getPhone(),
                ctm.getMovel(),
                ctm.getCep(),
                ctm.getAddress(),
                ctm.getComplement(),
                ctm.getNumberHouse(),
                ctm.getCity(),
                ctm.getStreet(),
                ctm.getState()

            });
        }
    }//GEN-LAST:event_btn_search_describeActionPerformed

    private void txt_describe_ccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_describe_ccKeyReleased
        // Capture text digit
        String name = "%" + txt_describe_cc.getText() + "%";

        CustomersDAO cdao = new CustomersDAO();
        // get String name passed -> sql
        List<Customers> list = cdao.listSearchFilter(name);
        // Call DefaultTableModel
        DefaultTableModel dtb = (DefaultTableModel) table.getModel();
        // Set Colums rows
        dtb.setNumRows(0);
        // for 
        for (Customers ctm : list) {
            // put dtb -> list
            dtb.addRow(new Object[]{
                ctm.getId(),
                ctm.getName(),
                ctm.getRg(),
                ctm.getCpf(),
                ctm.getEmail(),
                ctm.getPhone(),
                ctm.getMovel(),
                ctm.getCep(),
                ctm.getAddress(),
                ctm.getComplement(),
                ctm.getNumberHouse(),
                ctm.getCity(),
                ctm.getStreet(),
                ctm.getState()

            });
        }
    }//GEN-LAST:event_txt_describe_ccKeyReleased

    private void txt_describeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_describeKeyPressed
//        // if event key equals ENTER 
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            // Capture this.name in txt_name
//            String name = txt_describe.getText();
//            Customers ctm = new Customers();
//            CustomersDAO cdao = new CustomersDAO();
//            // New customer = cdao -> method search
//            ctm = cdao.Search(name);
//            // if name != null
//            if (ctm.getName() != null) {
//                txt_id.setText(String.valueOf(ctm.getId()));
//                txt_describe.setText(ctm.getName());
//                txt_price.setText(ctm.getRg());
//                txt_cpf.setText(ctm.getCpf());
//                txt_stock.setText(ctm.getEmail());
//                txt_phone.setText(ctm.getPhone());
//                txt_movel.setText(ctm.getMovel());
//                txt_cep.setText(ctm.getCep());
//                txt_address.setText(ctm.getAddress());
//                txt_number.setText(String.valueOf(ctm.getNumberHouse()));
//                txt_complement.setText(ctm.getComplement());
//                txt_city.setText(ctm.getCity());
//                txt_street.setText(ctm.getStreet());
//                cbx_employees.setSelectedItem(ctm.getState());
//            } else {
//                JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
//            }
//        }

    }//GEN-LAST:event_txt_describeKeyPressed

    private void txt_describeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_describeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_describeActionPerformed

    private void txt_describeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_describeMouseClicked

    }//GEN-LAST:event_txt_describeMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        panelGuides.setSelectedIndex(0);
        txt_id.setText(table.getValueAt(table.getSelectedRow(), 0).toString());
        txt_describe.setText(table.getValueAt(table.getSelectedRow(), 1).toString());
        txt_price.setText(table.getValueAt(table.getSelectedRow(), 2).toString());
        txt_stock.setText(table.getValueAt(table.getSelectedRow(), 3).toString());
        
        // Set Supplier and method Search -> Reset ComboBox no risk duplicate
        Suppliers sup = new Suppliers();
        SuppliersDAO sdao = new SuppliersDAO();
        // search value 
        sup = sdao.Search(table.getValueAt(table.getSelectedRow(), 4).toString());
        cbx_suppliers.removeAllItems();
        // add in model comboBox
        cbx_suppliers.getModel().setSelectedItem(sup);
        
    }//GEN-LAST:event_tableMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
//        // edit and save
//        Customers ct = new Customers();
//
//        ct.setName(txt_describe.getText());
//        ct.setRg(txt_price.getText());
//        ct.setCpf(txt_cpf.getText());
//        ct.setEmail(txt_stock.getText());
//        ct.setPhone(txt_phone.getText());
//        ct.setMovel(txt_movel.getText());
//        ct.setCep(txt_cep.getText());
//        ct.setAddress(txt_address.getText());
//        ct.setNumberHouse(Integer.parseInt(txt_number.getText()));
//        ct.setComplement(txt_complement.getText());
//        ct.setCity(txt_city.getText());
//        ct.setStreet(txt_street.getText());
//        ct.setState(cbx_employees.getSelectedItem().toString());
//        ct.setId(Integer.valueOf(txt_id.getText()));
//
//        // Call method saveDAO
//        CustomersDAO cdao = new CustomersDAO();
//        cdao.edit(ct);
//        CleanFields cls = new CleanFields();
//        cls.cleanForm(panelPersonalData);

    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        //Action delete customer for id
        Customers ctm = new Customers();
        ctm.setId(Integer.parseInt(txt_id.getText()));
        CustomersDAO cdao = new CustomersDAO();
        cdao.delete(ctm);
        // clear fields 
        CleanFields clean = new CleanFields();
        clean.cleanForm(panelPersonalData);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void cbx_suppliersAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbx_suppliersAncestorAdded

    }//GEN-LAST:event_cbx_suppliersAncestorAdded

    private void cbx_suppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_suppliersMouseClicked

    }//GEN-LAST:event_cbx_suppliersMouseClicked

    private void cbx_suppliersComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbx_suppliersComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_suppliersComponentShown

    private void tableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAncestorAdded
        // access data object
        SuppliersDAO pdao = new SuppliersDAO();
        // create list access
        List<Suppliers> listBox = pdao.listSuppliers();
        // clear comboBox
        cbx_suppliers.removeAllItems();
        // Add Suppliers in list
        for (Suppliers s : listBox) {
            // add item comboBox -> Caution disable type variable comboBox (String -> Null)
            cbx_suppliers.addItem(s);
        }


    }//GEN-LAST:event_tableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search_describe;
    private javax.swing.JComboBox cbx_suppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelConsult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelConsultClient;
    private javax.swing.JTabbedPane panelGuides;
    private javax.swing.JPanel panelPersonalData;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_describe;
    private javax.swing.JTextField txt_describe_cc;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
